use oxpm_lockfile::{Lockfile, Package, VERSION};
use oxpm_common::SourceType;

fn de<T: serde::de::DeserializeOwned>(toml_str: &str) -> T {
	toml::from_str(toml_str).expect("failed to deserialize")
}

#[test]
fn new_lockfile() {
	let lf = Lockfile::new();
	assert_eq!(lf.version, VERSION);
	assert!(lf.packages.is_empty());
}

#[test]
fn parse_empty_lockfile() {
	let lf = Lockfile::load_from_str("version = 1\n").expect("parse");
	assert_eq!(lf.version, 1);
	assert!(lf.packages.is_empty());
}

#[test]
fn parse_with_comment_header() {
	let input = r#"# This file is automatically @generated by oxpm.
# It is not intended for manual editing.

version = 1

[[package]]
name = "lodash"
version = "4.17.21"
source = "registry+https://registry.npmjs.org"
"#;
	let lf = Lockfile::load_from_str(input).expect("parse");
	assert_eq!(lf.version, 1);
	assert_eq!(lf.packages.len(), 1);
	assert_eq!(lf.packages[0].name.as_str(), "lodash");
}

#[test]
fn parse_multiple_packages() {
	let input = r#"
version = 1

[[package]]
name = "lodash"
version = "4.17.21"
source = "registry+https://registry.npmjs.org"
integrity = "sha512-abc"

[[package]]
name = "express"
version = "4.18.2"
source = "registry+https://registry.npmjs.org"
integrity = "sha512-def"
dependencies = ["accepts@1.3.8", "body-parser@1.20.1"]
devDependencies = ["jest@^29.0.0"]
"#;
	let lf = Lockfile::load_from_str(input).expect("parse");
	assert_eq!(lf.packages.len(), 2);
	assert_eq!(lf.packages[0].name.as_str(), "lodash");
	assert_eq!(lf.packages[1].name.as_str(), "express");
	let dev = lf.packages[1].dev_dependencies.as_ref().expect("dev");
	assert_eq!(dev.len(), 1);
	assert_eq!(dev[0].as_str(), "jest@^29.0.0");
	let deps = lf.packages[1].dependencies.as_ref().expect("deps");
	assert_eq!(deps.len(), 2);
}

#[test]
fn parse_git_source() {
	let input = r#"
version = 1

[[package]]
name = "my-fork"
version = "1.0.0"
source = "git+https://github.com/user/fork#abcdef"
"#;
	let lf = Lockfile::load_from_str(input).expect("parse");
	assert_eq!(
		lf.packages[0].source.to_source_string().as_str(),
		"git+https://github.com/user/fork#abcdef"
	);
}

#[test]
fn parse_invalid_toml() {
	let err = Lockfile::load_from_str("not valid toml [[[").unwrap_err();
	assert!(matches!(err, oxpm_lockfile::Error::Parse(_)));
}

#[test]
fn roundtrip() {
	let input = r#"
version = 1

[[package]]
name = "lodash"
version = "4.17.21"
source = "registry+https://registry.npmjs.org"
integrity = "sha512-abc"
dependencies = ["dep-a@1.0.0"]

[[package]]
name = "@types/node"
version = "20.11.0"
source = "registry+https://registry.npmjs.org"
integrity = "sha512-xyz"
devDependencies = ["jest@^29.0.0"]
"#;
	let lf = Lockfile::load_from_str(input).expect("parse");
	let serialized = lf.to_string_pretty().expect("serialize");
	let reparsed = Lockfile::load_from_str(&serialized).expect("reparse");
	assert_eq!(reparsed.version, lf.version);
	assert_eq!(reparsed.packages.len(), lf.packages.len());
	for (a, b) in reparsed.packages.iter().zip(lf.packages.iter()) {
		assert_eq!(a.name, b.name);
		assert_eq!(a.version.to_string(), b.version.to_string());
		assert_eq!(a.source, b.source);
		assert_eq!(a.integrity, b.integrity);
		assert_eq!(a.dev_dependencies, b.dev_dependencies);
	}
}

#[test]
fn to_string_pretty_has_comment_header() {
	let lf = Lockfile::new();
	let output = lf.to_string_pretty().expect("serialize");
	assert!(output.starts_with("# This file is automatically @generated by oxpm."));
	assert!(output.contains("# It is not intended for manual editing."));
}

#[test]
fn save_and_load_file() {
	let dir = std::env::temp_dir().join("oxpm_lockfile_test");
	std::fs::create_dir_all(&dir).expect("mkdir");
	let path = dir.join("oxpm-lock.toml");

	let mut lf = Lockfile::new();
	lf.packages.push(Package {
		name: "test-pkg".into(),
		version: "1.2.3".parse().expect("version"),
		source: SourceType::parse("registry+https://registry.npmjs.org"),
		integrity: Some("sha512-test".into()),
		dependencies: None,
		dev_dependencies: None,
		optional_dependencies: None,
		peer_dependencies: None,
		bin: None,
		engines: None,
		os: None,
		cpu: None,
	});

	lf.save_to_path(&path).expect("save");
	let loaded = Lockfile::load_from_path(&path).expect("load");
	assert_eq!(loaded.packages.len(), 1);
	assert_eq!(loaded.packages[0].name.as_str(), "test-pkg");

	std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn package_with_all_fields() {
	let input = r#"
version = 1

[[package]]
name = "typescript"
version = "5.3.3"
source = "registry+https://registry.npmjs.org"
integrity = "sha512-full"
dependencies = ["dep@1.0.0"]
bin = true
devDependencies = ["jest@^29.0.0"]
optionalDependencies = ["fsevents@^2.0.0"]
peerDependencies = ["react@^18.0.0"]
engines = { node = ">=14.17" }
os = ["linux", "darwin"]
cpu = ["x64", "arm64"]
"#;
	let lf = Lockfile::load_from_str(input).expect("parse");
	let pkg = &lf.packages[0];
	assert_eq!(pkg.name.as_str(), "typescript");
	assert!(pkg.bin.is_some());
	let dev = pkg.dev_dependencies.as_ref().expect("dev");
	assert_eq!(dev.len(), 1);
	assert_eq!(dev[0].as_str(), "jest@^29.0.0");
	let peer = pkg.peer_dependencies.as_ref().expect("peer");
	assert_eq!(peer.len(), 1);
	assert_eq!(peer[0].as_str(), "react@^18.0.0");
	let engines = pkg.engines.as_ref().expect("engines");
	assert_eq!(engines.get("node").expect("node").as_str(), ">=14.17");
	let os = pkg.os.as_ref().expect("os");
	assert_eq!(os.len(), 2);
	let cpu = pkg.cpu.as_ref().expect("cpu");
	assert_eq!(cpu.len(), 2);
}

#[test]
fn parse_same_name_different_versions() {
	let input = r#"
version = 1

[[package]]
name = "lodash"
version = "4.17.20"
source = "registry+https://registry.npmjs.org"

[[package]]
name = "lodash"
version = "4.17.21"
source = "registry+https://registry.npmjs.org"

[[package]]
name = "lodash"
version = "4.17.19"
source = "registry+https://registry.npmjs.org"
"#;
	let lf = Lockfile::load_from_str(input).expect("parse");
	assert_eq!(lf.packages.len(), 3);
	assert_eq!(lf.packages[0].version.to_string(), "4.17.20");
	assert_eq!(lf.packages[1].version.to_string(), "4.17.21");
	assert_eq!(lf.packages[2].version.to_string(), "4.17.19");
}

#[test]
fn serialize_skips_empty_packages() {
	let lf = Lockfile::new();
	let output = lf.to_string_pretty().expect("serialize");
	assert!(!output.contains("packages"));
}

#[test]
fn serialize_includes_version() {
	let mut lf = Lockfile::new();
	lf.packages.push(Package {
		name: "test".into(),
		version: "1.0.0".parse().unwrap(),
		source: SourceType::parse("registry+https://registry.npmjs.org"),
		integrity: None,
		dependencies: None,
		dev_dependencies: None,
		optional_dependencies: None,
		peer_dependencies: None,
		bin: None,
		engines: None,
		os: None,
		cpu: None,
	});
	let output = lf.to_string_pretty().expect("serialize");
	assert!(output.contains("version = "));
	assert!(output.contains("[[package]]"));
}

#[test]
fn load_from_path_not_found() {
	let result = Lockfile::load_from_path("non_existent_path.toml");
	assert!(result.is_err());
}

#[test]
fn save_to_path_and_load() {
	let dir = std::env::temp_dir().join("oxpm_lockfile_save_test");
	std::fs::create_dir_all(&dir).expect("mkdir");
	let path = dir.join("test-lock.toml");

	let mut lf = Lockfile::new();
	lf.packages.push(Package {
		name: "lodash".into(),
		version: "4.17.21".parse().unwrap(),
		source: SourceType::parse("registry+https://registry.npmjs.org"),
		integrity: None,
		dependencies: Some(vec!["dep-a@1.0.0".into()]),
		dev_dependencies: None,
		optional_dependencies: None,
		peer_dependencies: None,
		bin: None,
		engines: None,
		os: None,
		cpu: None,
	});

	lf.save_to_path(&path).expect("save");
	let loaded = Lockfile::load_from_path(&path).expect("load");
	assert_eq!(loaded.packages.len(), 1);
	assert_eq!(loaded.packages[0].name.as_str(), "lodash");
	assert_eq!(loaded.packages[0].dependencies.as_ref().unwrap()[0].as_str(), "dep-a@1.0.0");

	std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn dependencies_roundtrip() {
	let pkg: Package = de(r#"
name = "multi-deps"
version = "1.0.0"
source = "registry+https://registry.npmjs.org"
dependencies = ["a@1.0.0", "b@2.0.0", "@scope/pkg@3.0.0"]
devDependencies = ["dev@1.0.0"]
optionalDependencies = ["opt@1.0.0"]
peerDependencies = ["peer@1.0.0"]
"#);
	let serialized = toml::to_string(&pkg).expect("serialize");
	let reparsed: Package = de(&serialized);
	assert_eq!(pkg.dependencies, reparsed.dependencies);
	assert_eq!(pkg.dev_dependencies, reparsed.dev_dependencies);
	assert_eq!(pkg.optional_dependencies, reparsed.optional_dependencies);
	assert_eq!(pkg.peer_dependencies, reparsed.peer_dependencies);
}

#[test]
fn engines_roundtrip() {
	let pkg: Package = de(r#"
name = "engines-test"
version = "1.0.0"
source = "registry+https://registry.npmjs.org"
engines = { node = ">=16", npm = ">=8" }
"#);
	let serialized = toml::to_string(&pkg).expect("serialize");
	let reparsed: Package = de(&serialized);
	assert_eq!(
		pkg.engines.as_ref().unwrap().get("node").unwrap().as_str(),
		">=16"
	);
	assert_eq!(
		reparsed.engines.as_ref().unwrap().get("npm").unwrap().as_str(),
		">=8"
	);
}

#[test]
fn bin_true_serialized() {
	let pkg = Package {
		name: "has-bin".into(),
		version: "1.0.0".parse().unwrap(),
		source: SourceType::parse("registry+https://registry.npmjs.org"),
		integrity: None,
		dependencies: None,
		dev_dependencies: None,
		optional_dependencies: None,
		peer_dependencies: None,
		bin: Some(true),
		engines: None,
		os: None,
		cpu: None,
	};
	let serialized = toml::to_string(&pkg).expect("serialize");
	assert!(serialized.contains("bin = true"));
}

#[test]
fn parse_with_all_constraints() {
	let input = r#"
version = 1

[[package]]
name = "complex-pkg"
version = "2.0.0"
source = "registry+https://registry.npmjs.org"
engines = { node = ">=18", npm = ">=9" }
os = ["linux", "darwin"]
cpu = ["x64", "arm64"]
"#;
	let lf = Lockfile::load_from_str(input).expect("parse");
	let pkg = &lf.packages[0];
	let engines = pkg.engines.as_ref().expect("engines");
	assert_eq!(engines.get("node").expect("node").as_str(), ">=18");
	assert_eq!(engines.get("npm").expect("npm").as_str(), ">=9");
	let os = pkg.os.as_ref().expect("os");
	assert_eq!(os.len(), 2);
	let cpu = pkg.cpu.as_ref().expect("cpu");
	assert_eq!(cpu.len(), 2);
}