[package]
name = "oxpm_semver"
version = "0.1.0"
description = "semver version for oxpm"
authors.workspace = true
license.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
thiserror.workspace = true
smol_str.workspace = true
serde.workspace = true
url.workspace = true

ecow = { version = "0.2.6", features = ["serde"] }

[dev-dependencies]
serde_json = "1"
criterion = "0.8.2"

[[bench]]
name = "parse"
harness = false
