[workspace]
members = ["crates/*"]
resolver = "2"


[workspace.package]
authors = ["wuliya <3369906077@qq.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/puniyu/oxpm"
repository = "https://github.com/puniyu/oxpm"
edition = "2024"
rust-version = "1.88.0"

[workspace.dependencies]
thiserror = { version = "2.0.18" }
serde = { version = "1.0.228", features = ["derive"] }
smol_str = { version = "0.3.6", features = ["serde"] }
ecow = { version = "0.2.6", features = ["serde"] }
url = { version = "2.5.8", features = ["serde"] }
serde_json = { version = "1.0.149" }
indexmap = { version = "2.9", features = ["serde"] }
toml = { version = "1.1.2" }
reqwest = { version = "0.13.3", features = ["json"] }
bytes = { version = "1.11.1" }
async-trait = { version = "0.1.89" }
sugar_path = { version = "3.0.0", features = ["cached_current_dir"] }
tar = { version = "0.4" }
flate2 = { version = "1.1" }
blake3 = { version = "1.8.5" }
cargo_metadata = { version = "0.23.1" }

tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
rayon = { version = "1.12.0" }

oxpm_source = { version = "0.1.0", path = "./crates/oxpm_source" }
oxpm_semver = { version = "0.1.0", path = "./crates/oxpm_semver" }
oxpm_version = { version = "0.1.0", path = "./crates/oxpm_version" }
oxpm_dep = { version = "0.1.0", path = "./crates/oxpm_dep" }
oxpm_file = { version = "0.1.0", path = "./crates/oxpm_file" }
oxpm_git = { version = "0.1.0", path = "./crates/oxpm_git" }
oxpm_link = { version = "0.1.0", path = "./crates/oxpm_link" }
oxpm_tarball = { version = "0.1.0", path = "./crates/oxpm_tarball" }
oxpm_config = { version = "0.1.0", path = "./crates/oxpm_config" }
oxpm_package_json = { version = "0.1.0", path = "./crates/oxpm_package_json" }
oxpm_lockfile = { version = "0.1.0", path = "./crates/oxpm_lockfile" }
oxpm_npm = { version = "0.1.0", path = "./crates/oxpm_npm" }
oxpm_registry = { version = "0.1.0", path = "./crates/oxpm_registry" }
oxpm_resolver = { version = "0.1.0", path = "./crates/oxpm_resolver" }
oxpm_path = { version = "0.1.0", path = "./crates/oxpm_path" }
oxpm_store = { version = "0.1.0", path = "./crates/oxpm_store" }
oxpm_dir_link = { version = "0.1.0", path = "./crates/oxpm_dir_link" }


[profile.release]
lto = "fat"
opt-level = "z"
incremental = false

[profile.dev]
lto = false
opt-level = 1
incremental = true
