[package]
name = "oxpm_common"
version = "0.1.0"
description = "common for oxpm"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
url.workspace = true
smol_str.workspace = true
thiserror.workspace = true
sugar_path.workspace = true


