[package]
name = "oxpm_tar"
version = "0.1.0"
description = "A tar implementation for Oxpm"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
thiserror.workspace = true
tar.workspace = true
flate2.workspace = true

walkdir = "2"

zstd = { version = "0.13.3", optional = true }
bzip2 = { version = "0.6.1", optional = true }

[features]
default = ["zstd", "bz2"]
zstd = ["dep:zstd"]
bz2 = ["dep:bzip2"]
