[package]
name = "oxpm_file"
version = "0.1.0"
edition.workspace = true

[dependencies]
oxpm_source.workspace = true
oxpm_resolver.workspace = true
oxpm_dep.workspace = true
oxpm_package_json.workspace = true
serde.workspace = true
smol_str.workspace = true
sugar_path.workspace = true
thiserror.workspace = true

async-trait.workspace = true
tokio.workspace = true