use std::path::Path;

use serde::{Deserialize, Serialize};

mod version;
#[doc(inline)]
pub use version::VERSION;
mod package;
#[doc(inline)]
pub use package::Package;
mod error;
pub use error::Error;

pub type Result<T> = std::result::Result<T, Error>;

const COMMENT_MSG: &str =
	"# This file is automatically @generated by oxpm.\n# It is not intended for manual editing.\n";

/// oxpm 锁文件的完整表示，使用 TOML 格式
///
/// 文件名为 `oxpm-lock.toml`，用于锁定 node 生态依赖的精确版本
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Lockfile {
	/// 锁文件格式版本号。
	pub version: u32,
	/// 所有锁定的包列表。
	#[serde(default, rename = "package")]
	pub packages: Vec<Package>,
}

impl Default for Lockfile {
	#[inline]
	fn default() -> Self {
		Self::new()
	}
}

impl Lockfile {
	pub fn new() -> Self {
		Self { version: VERSION, packages: Vec::new() }
	}

	pub fn load_from_path(path: impl AsRef<Path>) -> Result<Self> {
		let content = std::fs::read_to_string(path)?;
		Self::load_from_str(&content)
	}

	pub fn load_from_str(content: &str) -> Result<Self> {
		let lockfile = toml::from_str(content)?;
		Ok(lockfile)
	}

	pub fn save_to_path(&self, path: impl AsRef<Path>) -> Result<()> {
		let content = self.to_string_pretty()?;
		std::fs::write(path, content)?;
		Ok(())
	}

	pub fn to_string_pretty(&self) -> Result<String> {
		let body = toml::to_string_pretty(self)?;
		Ok(format!("{COMMENT_MSG}\n{body}"))
	}
}